spring:
  application:
    name: liOJ

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root12345678
    url: jdbc:mysql://localhost:3306/liOJ
  session:
    timeout: 86400 # session过期时间

server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 代码沙箱配置
codeSandbox:
  type: example # 沙箱类型, 通过配置切换, 不需要修改代码


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.lili.controller

