spring:
  application:
    name: user-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root12345678
    url: jdbc:mysql://localhost:3306/web_center
  session:
    timeout: 86400 # session过期时间

server:
  port: 8080

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
