spring:
  application:
    name: user-center

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root12345678
    url: jdbc:mysql://localhost:3306/web_center

server:
  port: 8080


